# Generated by Django 3.2 on 2021-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinister',
            name='sister_type',
            field=models.CharField(choices=[('insendie', 'insendie'), ('accident', 'accident')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
