# Generated by Django 3.2 on 2021-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinister', '0002_sinister_sister_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinister',
            name='sister_type',
            field=models.CharField(choices=[('incendie', 'incendie'), ('accident', 'accident')], max_length=20),
        ),
    ]
