# Generated by Django 3.2 on 2021-04-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinister', '0003_alter_sinister_sister_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinister',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
