# Generated by Django 3.2 on 2021-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinister', '0004_sinister_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinister',
            name='damage',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinister',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
