# Generated by Django 3.2 on 2021-04-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinister', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinister',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sinister.category'),
        ),
    ]
